// spa/vue/src/component/CategoryPicker.vue
<template>
<ul class="ui-categorypicker">
    <li 
        v-for="(index, item) in datasource" 
        v-bind:style="{'background': item.color}"
        v-bind:class="{'selected': item.id == value}"
        v-on:click="itemClick(index)"
    >{{ item.title }}</li>
</ul>
</template>


<script>
export default {
    props: {
        value: {
            default: null
        },
        datasource: {
            default: []
        }
    },

    methods: {
        itemClick: function (index) {
            this.value = this.datasource[index].id;
        }
    }
}
</script>


<style>
.ui-categorypicker {
    display: inline-block;
}

.ui-categorypicker li {
    display: inline-block;
    margin: 5px 5px 5px 0;
    padding: 5px;
    border-radius: 3px;
    cursor: pointer;
    color: #fff;
}

.ui-categorypicker li a {
    color: #fff;
    text-decoration: none;
}

.ui-categorypicker .selected {
    box-shadow: 0 0 0 2px #ddd inset;
}
</style>

// spa/redux-react/src/component/CategoryPicker.js
import React, {Component, PropTypes} from 'react'

export default class CategoryPicker extends Component {
    constructor(props) {
        super(props);
        
        this.itemClick = this.itemClick.bind(this);
        this.state = {
            value: this.props.initValue
        };
    }

    componentWillReceiveProps(nextProps) {
        this.setState({
            value: nextProps.initValue
        });
    }

    render() {
        let category = this.props.value;

        return (
            <ul className="ui-categorypicker">
            {this.props.datasource.map((item, index) => 
                <li className={item.id == this.state.value ? 'selected' : ''}
                    style={{background: item.color}}
                    onClick={this.itemClick}
                    data-index={index}
                >
                    {item.title}
                </li>
            )}
            </ul>
        );
    }

    itemClick(e) {
        let index = +e.target.getAttribute('data-index');
        let item = this.props.datasource[index];
        let value = item && item.id;

        if (this.state.value != value) {
            this.setState({value});
        }
    }
}
